/*
 * EDIT THIS FILE to update fundraising totals, links, and the supporter wall.
 * Confirmed raised and pending employer matching must always remain separate.
 */
window.SITE_DATA = {
  goal: 3000,
  confirmedRaised: 2927.02,
  pendingMatch: 2383,

  campaignNote: "Julianne London 2027",
  venmoUsername: "christina0318",
  venmoUrl: "https://venmo.com/u/christina0318",
  officialFundraisingUrl: "https://justgiving.com/page/christinalee",
  foundationUrl: "https://mollyrosefoundation.org",

  contributionFormUrl: "https://forms.gle/ZRbpAAGjjGLEJB5N8",

  /* Optional launch-day message from the final copy document. */
  showLaunchCallout: false,

  supporters: [
    {
      name: "Kevin K.",
      contribution: 500,
      date: "August 2026",
      matchAmount: 500,
      matchStatus: "pending",
      employer: "",
      note: "LFG!!! 💥 🎉",
    },
    {
      name: "William N.",
      contribution: 500,
      date: "August 2026",
      matchAmount: 500,
      matchStatus: "pending",
      employer: "",
      note: "For those who we lost too soon and for those who are still here to keep them alive in our memories and our hearts.",
    },
    {
      name: "Anonymous",
      contribution: 100,
      date: "August 2026",
      matchAmount: 100,
      matchStatus: "pending",
      employer: "",
      note: "",
    },
    {
      name: "Anonymous",
      contribution: 250,
      date: "August 2026",
      matchAmount: 250,
      matchStatus: "pending",
      employer: "",
      note: "",
    },
    {
      name: "Anonymous",
      contribution: 100,
      date: "August 2026",
      matchAmount: 100,
      matchStatus: "pending",
      employer: "",
      note: "",
    },
    {
      name: "Anonymous",
      contribution: 50,
      date: "August 2026",
      matchAmount: 50,
      matchStatus: "pending",
      employer: "",
      note: "",
    },
    {
      name: "Lou L.",
      contribution: 250,
      date: "August 2026",
      matchAmount: 250,
      matchStatus: "pending",
      employer: "",
      note: "May Julianne's memory continue to open doors for others who are struggling. Proud to support this cause.",
    },
    {
      name: "Anonymous",
      contribution: 20,
      date: "August 2026",
      matchAmount: 20,
      matchStatus: "pending",
      employer: "",
      note: "",
    },
    {
      name: "Anonymous",
      contribution: 20,
      date: "August 2026",
      matchAmount: 20,
      matchStatus: "pending",
      employer: "",
      note: "",
    },
    {
      name: "Anonymous",
      contribution: 18,
      date: "August 2026",
      matchAmount: 18,
      matchStatus: "pending",
      employer: "",
      note: "",
    },
    {
      name: "Anonymous",
      contribution: 40,
      date: "August 2026",
      matchAmount: 40,
      matchStatus: "pending",
      employer: "",
      note: "",
    },
    {
      name: "Nicole K.",
      contribution: 50,
      date: "August 2026",
      matchAmount: 50,
      matchStatus: "pending",
      employer: "",
      note: "",
    },
    {
      name: "Norman C.",
      contribution: 50,
      date: "August 2026",
      matchAmount: 50,
      matchStatus: "pending",
      employer: "",
      note: "I’m inspired by how through the pain you've continued to shine bright. I know how hard it must be to even smile but you've done such a great job. Thanks for sharing Julianne’s story - best of luck in London!",
    },
    {
      name: "Hope S.",
      contribution: 30,
      date: "August 2026",
      matchAmount: 30,
      matchStatus: "pending",
      employer: "",
      note: "❤️❤️❤️",
    },
    {
      name: "Michel",
      contribution: 100,
      date: "August 2026",
      matchAmount: 100,
      matchStatus: "pending",
      employer: "",
      note: "We’ll all be cheering you on Christina! Have a great run in London and most importantly of all, enjoy the experience 😊",
    },
    {
      name: "Anonymous",
      contribution: 250,
      date: "August 2026",
      matchAmount: 250,
      matchStatus: "pending",
      employer: "",
      note: "",
    },
    {
      name: "Ariane E.",
      contribution: 25,
      date: "August 2026",
      matchAmount: 25,
      matchStatus: "pending",
      employer: "",
      note: "",
    },
    {
      name: "Anonymous",
      contribution: 30,
      date: "August 2026",
      matchAmount: 30,
      matchStatus: "pending",
      employer: "",
      note: "",
    },
    {
      name: "Anonymous",
      contribution: 200,
      date: "August 2026",
      matchAmount: 0,
      matchStatus: "",
      employer: "",
      note: "",
    },
    {
      name: "Kate P.",
      contribution: 100,
      date: "August 2026",
      matchAmount: 0,
      matchStatus: "",
      employer: "",
      note: "You make Julianne proud every day! 💖",
    },
    {
      name: "Ericka W.",
      contribution: 50,
      date: "August 2026",
      matchAmount: 0,
      matchStatus: "",
      employer: "",
      note: "Your run, in honor of Julianne ❤️",
    },
    {
      name: "Sam L.",
      contribution: 194.02,
      date: "August 2026",
      matchAmount: 0,
      matchStatus: "",
      employer: "",
      note: "26.2 Miles for Julianne 🤍🤍🤍🤍🤍🫶🏻🫶🏻🫶🏻",
    },
  ],
};
